{{ config(materialized = 'table')}}

with HEALTH as (
    select * 
    from {{ ref('base_health')}}
)

health_model as (
    select
        HEALTH._AIRBYTE_RAW_ID,
        HEALTH.LOCATION_KEY,
        iff(HEALTH.LIFE_EXPECTANCY = null, 0, HEALTH.LIFE_EXPECTANCY) as LIFE_EXPECTANCY,
        iff(HEALTH.NURSES_PER_1000 = null, 0, HEALTH.NURSES_PER_1000) as NURSES_PER_1000,
        iff(HEALTH.PHYSICIANS_PER_1000 = null, 0, HEALTH.PHYSICIANS_PER_1000) as PHYSICIANS_PER_1000,
        iff(HEALTH.POLLUTION_MORTALITY_RATE = null, 0, HEALTH.POLLUTION_MORTALITY_RATE) as POLLUTION_MORTALITY_RATE,
        iff(HEALTH.HOSPITAL_BEDS_PER_1000 = null, 0, HEALTH.HOSPITAL_BEDS_PER_1000) as HOSPITAL_BEDS_PER_1000,
        iff(HEALTH.ADULT_FEMALE_MORTALITY_RATE = null, 0, HEALTH.ADULT_FEMALE_MORTALITY_RATE) as ADULT_FEMALE_MORTALITY_RATE,
        iff(HEALTH.ADULT_MALE_MORTALITY_RATE = null, 0, HEALTH.ADULT_MALE_MORTALITY_RATE) as ADULT_MALE_MORTALITY_RATE
    from HEALTH
)

select * from health_model
